[build]
builder = "NIXPACKS"

[deploy]
startCommand = "echo 'Please configure backend and frontend as separate services in Railway dashboard'"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
